[accounts]
remote = "https://api.mainnet-beta.solana.com/"
lifecycle = "replica"
allowed-programs = []
max-monitored-accounts = 2048

[accounts.commit]
frequency_millis = 100000000
compute_unit_price = 1000000

[accounts.payer]
init_sol = 1000

[accounts.db]
db-size = 3221225472
block-size = "block256"
index-map-size = 67108864
max-snapshots = 4
snapshot-frequency = 20000

[rpc]
addr = "0.0.0.0"
port = 8899
max-ws-connections = 16384

[geyser_grpc]
addr = "0.0.0.0"
port = 10000

[validator]
millis_per_slot = 50
sigverify = true
country_code = "US"

[ledger]
reset = true
size = 107374182400

[metrics]
enabled = true
system_metrics_tick_interval_secs = 30
addr = "0.0.0.0"
port = 9000
